[package]
name = "const_queue"
version = "0.1.0"
authors = ["Rincewound <aaaargh@minddebugger.com>"]
edition = "2018"
license = "0BSD"
description = "A stack-only, no_std queue using const generics"
homepage = "https://github.com/rincewound/const_queue"
repository = "https://github.com/rincewound/const_queue"
documentation = "https://github.com/rincewound/const_queue"
readme = "Readme.md"
keywords = ["Data-structures", "no-std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
