[package]
name = "const_queue"
version = "0.1.0"
authors = ["Rincewound <aaaargh@minddebugger.com>"]
edition = "2018"
license = "BSD"
description = "A stack-only, no_std queue using const generics"
homepage = "https://github.com/rincewound/fsm_rs"
repository = "https://github.com/rincewound/fsm_rs"
documentaation = "https://github.com/rincewound/fsm_rs"
readme = "Readme.md"
keywords = ["Data structures", "no_std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
